services:
  filesentry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs  # Mount the entire configs folder
    environment:
      DRY_RUN: "${DRY_RUN:-false}"
      WATCH_DIR: "/app/data/watcher"
