services:
  filesentry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data 
      - ./rules.yaml:/app/rules.yaml
    environment:
      DRY_RUN: "${DRY_RUN:-false}"
      WATCH_DIR: "/app/data/watcher"
