rules:
  - name: "Sort Images"
    watch: "/app/data/watcher"
    filters:
      - extension: [".jpg", ".png"]
      - exclude: "(\\.tmp$|~$)"
    actions:
      - move: "/app/data/sorted/images"

  - name: "Organize PDFs"
    watch: "/app/data/watcher"
    filters:
      - extension: [".pdf"]
    actions:
      - move: "/app/data/sorted/docs"

  - name: "Backup Text Files"
    watch: "/app/data/watcher"
    filters:
      - extension: [".txt"]
    actions:
      - move: "/app/data/sorted/text_backups"

  - name: "Backup to S3"
    watch: "/app/data/watcher"
    filters:
      - extension: [".jpg", ".png"]
    actions:
      - move: "/app/data/sorted/images"
      - upload_to_s3: "s3://your-bucket-name/images/{{timestamp}}/{{filename}}"
